::PRM.Database.Defaults.Casual <-
{
	BeastPartsPriceMult = 140,
	BusinessReputationBadRate = 100,
	BusinessReputationGoodRate = 120,
	BuyPriceMult = 100,
	ChampionChanceAdditional = 1,
	ContractPaymentMult = 140,
	DailyWageMult = 90,
	FoodConsumptionMult = 90,
	HitpointsPerHourMult = 120,
	LocationResourcesMult = 110,
	LootRemovalChance = 0,
	PartyResourcesMult = 110,
	RarityMult = 120,
	RecruitsMult = 110,
	RelationChangeBadMult = 100,
	RelationChangeGoodMult = 110,
	RelationDecayBadMult = 100,
	RelationDecayGoodMult = 100,
	RepairSpeedMult = 100,
	SellPriceMult = 120,
	StashSize = 99,
	XPMult = 100,
};