::PRM.Database.Defaults.Challenging <-
{
	BeastPartsPriceMult = 150,
	BusinessReputationBadRate = 115,
	BusinessReputationGoodRate = 85,
	BuyPriceMult = 150,
	ChampionChanceAdditional = 3,
	ContractPaymentMult = 120,
	DailyWageMult = 130,
	FoodConsumptionMult = 110,
	HitpointsPerHourMult = 70,
	LocationResourcesMult = 140,
	LootRemovalChance = 30,
	PartyResourcesMult = 130,
	RarityMult = 70,
	RecruitsMult = 70,
	RelationChangeBadMult = 110,
	RelationChangeGoodMult = 90,
	RelationDecayBadMult = 80,
	RelationDecayGoodMult = 120,
	RepairSpeedMult = 50,
	StashSize = 60,
	SellPriceMult = 100,
	XPMult = 70,
};