::PRM.Database.Defaults.Challenging <-
{
	BeastPartsPriceMult = 150,
	BusinessReputationBadRate = 115,
	BusinessReputationGoodRate = 85,
	BuyPriceMult = 150,
	ChampionChanceAdditional = 3,
	ContractPaymentMult = 130,
	DailyWageMult = 120,
	EntityScaleChance = 25,
	FoodConsumptionMult = 110,
	HitpointsPerHourMult = 70,
	LocationResourcesMult = 140,
	LootRemovalChance = 15,
	PartyResourcesMult = 120,
	RarityMult = 80,
	RecruitsMult = 70,
	RelationChangeBadMult = 110,
	RelationChangeGoodMult = 90,
	RelationDecayBadMult = 90,
	RelationDecayGoodMult = 110,
	RepairSpeedMult = 50,
	SellPriceMult = 100,
	StashSize = 60,
	XPMult = 70,
};