::PRM.Database.Defaults.Unfair <-
{
	BeastPartsPriceMult = 175,
	BusinessReputationBadRate = 120,
	BusinessReputationGoodRate = 70,
	BuyPriceMult = 180,
	ChampionChanceAdditional = 6,
	ContractPaymentMult = 90,
	DailyWageMult = 170,
	EntityScaleChance = 65,
	FoodConsumptionMult = 140,
	HitpointsPerHourMult = 40,
	LocationResourcesMult = 200,
	LootRemovalChance = 50,
	PartyResourcesMult = 180,
	RarityMult = 40,
	RecruitsMult = 25,
	RelationChangeBadMult = 120,
	RelationChangeGoodMult = 80,
	RelationDecayBadMult = 60,
	RelationDecayGoodMult = 150,
	RepairSpeedMult = 25,
	SellPriceMult = 80,
	StashSize = 30,
	XPMult = 40,
};