::PRM.Database.Defaults.Unfair <-
{
	BeastPartsPriceMult = 150,
	BusinessReputationBadRate = 140,
	BusinessReputationGoodRate = 60,
	BuyPriceMult = 180,
	ChampionChanceAdditional = 6,
	ContractPaymentMult = 100,
	DailyWageMult = 170,
	FoodConsumptionMult = 120,
	HitpointsPerHourMult = 40,
	LocationResourcesMult = 180,
	LootRemovalChance = 65,
	PartyResourcesMult = 170,
	RarityMult = 40,
	RecruitsMult = 25,
	RelationChangeBadMult = 130,
	RelationChangeGoodMult = 80,
	RelationDecayBadMult = 60,
	RelationDecayGoodMult = 150,
	RepairSpeedMult = 25,
	SellPriceMult = 80,
	StashSize = 30,
	XPMult = 30,
};