::PRM.Database.Defaults.Unfair <-
{
	BeastPartsPriceMult = 175,
	BusinessReputationBadRate = 120,
	BusinessReputationGoodRate = 80,
	BuyPriceMult = 170,
	ChampionChanceAdditional = 6,
	ContractPaymentMult = 90,
	DailyWageMult = 140,
	EntityScaleChance = 65,
	FoodConsumptionMult = 140,
	HitpointsPerHourMult = 40,
	LocationResourcesMult = 150,
	LootRemovalChance = 25,
	PartyResourcesMult = 140,
	RarityMult = 40,
	RecruitsMult = 35,
	RelationChangeBadMult = 120,
	RelationChangeGoodMult = 80,
	RelationDecayBadMult = 80,
	RelationDecayGoodMult = 120,
	RepairSpeedMult = 25,
	SellPriceMult = 80,
	StashSize = 30,
	XPMult = 40,
};