::PRM.Database.Defaults.Vanilla <-
{
	BeastPartsPriceMult = 100,
	BusinessReputationBadRate = 100,
	BusinessReputationGoodRate = 100,
	BuyPriceMult = 100,
	ChampionChanceAdditional = 0,
	ContractPaymentMult = 100,
	DailyWageMult = 100,
	FoodConsumptionMult = 100,
	HitpointsPerHourMult = 100,
	LocationResourcesMult = 100,
	LootRemovalChance = 0,
	PartyResourcesMult = 100,
	RarityMult = 100,
	RecruitsMult = 100,
	RelationChangeBadMult = 100,
	RelationChangeGoodMult = 100,
	RelationDecayBadMult = 100,
	RelationDecayGoodMult = 100,
	RepairSpeedMult = 100,
	SellPriceMult = 100,
	StashSize = 99,
	XPMult = 100,
};